# Generated by Django 4.0.5 on 2022-06-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_article_options_alter_executors_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executors',
            name='name',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
