# Generated by Django 4.0.5 on 2022-08-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='Email')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
