# Generated by Django 4.0.5 on 2022-08-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_rename_user_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(db_index=True, default='A', max_length=40),
        ),
        migrations.AddField(
            model_name='myuser',
            name='surname',
            field=models.CharField(db_index=True, default='M', max_length=40),
        ),
    ]
