# Generated by Django 4.0.5 on 2022-08-12 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_myuser_name_myuser_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
