# Generated by Django 4.0.5 on 2022-08-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_article_executor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Executors',
        ),
    ]
